add help subcommand

diff --git a/.local/bin/exa b/.local/bin/exa
--- a/.local/bin/exa
+++ b/.local/bin/exa
@@ -1,10 +1,98 @@
 #!/usr/bin/env bash
 # shellcheck disable=SC2034,SC1090
+# shellcheck disable=SC2317
 
 source ~/.config/bash/lib/logger.sh
 source ~/.config/bash/lib/str/markup_unescape.sh
 source ~/.config/bash/lib/str/uri_params.sh
 source ~/.config/bash/lib/barg.sh
+
+function main {
+  read -r MELOC < <(realpath -LP "${0}")
+  read -r MEDIR < <(dirname "${MELOC}")
+  read -r MEAKA < <(basename "${MELOC}")
+  local show_usage=false
+  barg.parse "${@}" << BARG || show_usage=true
+  #[progname='${MEAKA}']
+  #[reqextras='true', extras='QUERY']
+  #[subcmds='=help']
+
+  @ t/timeout[num] |> "5" => EXA_TIMEOUT
+  @ T/tries[int] |> "5" => EXA_TRIES
+  @ c/cookies[str] => EXA_COOKIES
+  @ u/user-agent[str] |> "Mozilla/5.0 (X11; Linux x86_64; rv:132.0) Gecko/20100101 Firefox/132.0" => EXA_USER_AGENT
+  @ a/amount[int] |> "10" => EXA_RESULT_AMOUNT
+  @ m/no-color[bool] => EXA_NO_COLOR
+BARG
+
+  if ${show_usage}; then
+    printf 'Usage: exa [options] ...QUERY\n'
+    return
+  fi
+
+  if [ "${BARG_SUBCOMMAND}" == 'help' ]; then
+    show_help_message
+    return 1
+  fi
+
+  # shellcheck disable=SC2153
+  local query="${QUERY[*]}"
+
+  if ((EXA_RESULT_AMOUNT < 1)) || ((EXA_RESULT_AMOUNT > 100)); then
+    log i 'Invalid amount of results (%s), defaulting to 10' "${EXA_RESULT_AMOUNT}"
+    EXA_RESULT_AMOUNT=10
+  fi
+
+  declare -A grequest=()
+  grequest['query']="${query}"
+  grequest['tries']="${EXA_TRIES}"
+  grequest['cookies']="${EXA_COOKIES}"
+  grequest['timeout']="${EXA_TIMEOUT}"
+  grequest['user_agent']="${EXA_USER_AGENT}"
+
+  # google params
+  grequest['g_num']="${EXA_RESULT_AMOUNT}"
+
+  if ! google_search grequest; then
+    log e 'Failed to search google'
+    return 1
+  fi
+
+  for ((i = 0; i < GOOGLE_RESULTS; i++)); do
+    if [[ -t 1 ]] && ! ${EXA_NO_COLOR}; then
+      printf '\x1b[38;2;255;169;140m- What: \x1b[38;2;255;232;184m%s\n' "${GOOGLE_RESULT_TITLES[i]}"
+      printf '  \x1b[38;2;195;79;230mLink: \x1b[38;2;189;147;249m%s\x1b[0m\n' "${GOOGLE_RESULT_LINKS[i]}"
+    else
+      printf -- '- What: %s\n  Link: %s\n' "${GOOGLE_RESULT_TITLES[i]}" "${GOOGLE_RESULT_LINKS[i]}"
+    fi
+  done
+}
+
+function show_help_message {
+  local help_lines=(
+    "\x1b[1;34m${MEAKA}\x1b[0m: Command line tool for Google"
+    ""
+    "\x1b[1;34mUsage:\x1b[0m"
+    "  \x1b[38;5;14m${MEAKA}\x1b[0m [OPTIONS] ...QUERY"
+    "  \x1b[38;5;14m${MEAKA}\x1b[0m help"
+    ""
+    "\x1b[1;34mSubcommands:\x1b[0m"
+    "  help        Show this help message and exit"
+    ""
+    '\x1b[1;34mOptions:\x1b[0m'
+    '  -t, --tries \x1b[38;5;15m<int>\x1b[0m       Number of attempts to search Google (default: 5)'
+    '  -c, --cookies \x1b[38;5;15m<str>\x1b[0m     Cookies to send with the request'
+    '  -u, --user-agent \x1b[38;5;15m<str>\x1b[0m  User-agent string to send with the request (default: Mozilla/5.0)'
+    '  -a, --amount \x1b[38;5;15m<int>\x1b[0m      Number of results to return (default: 10)'
+    '  -n, --no-color          Disable color output'
+    ""
+    '\x1b[1;34mExamples:\x1b[0m'
+    "  ${MEAKA}"' site:en.wikipedia.org '\''intext:"ugliest colour"'\'
+    "  ${MEAKA}"' -t 10 -c "SKD=8KHnxKFrzuGRZfJ; EYW=c6kl8" 448c'
+  )
+
+  printf '%b\n' "${help_lines[@]}"
+}
 
 function google_search {
   declare -n request="${1}"
@@ -90,58 +178,6 @@ function google_search {
   declare -g GOOGLE_RESULT_LINKS
 
   return 0
-}
-
-function main {
-  local show_usage=false
-  barg.parse "${@}" << BARG || show_usage=true
-  #[progname='exa']
-  #[reqextras='true', extras='QUERY']
-
-  t/timeout[num] |> "5" => EXA_TIMEOUT
-  T/tries[int] |> "5" => EXA_TRIES
-  c/cookies[str] => EXA_COOKIES
-  u/user-agent[str] |> "Mozilla/5.0 (X11; Linux x86_64; rv:132.0) Gecko/20100101 Firefox/132.0" => EXA_USER_AGENT
-  a/amount[int] |> "10" => EXA_RESULT_AMOUNT
-  m/no-color[bool] => EXA_NO_COLOR
-BARG
-
-  if ${show_usage}; then
-    printf 'Usage: exa [options] ...QUERY\n'
-    return
-  fi
-
-  # shellcheck disable=SC2153
-  local query="${QUERY[*]}"
-
-  if ((EXA_RESULT_AMOUNT < 1)) || ((EXA_RESULT_AMOUNT > 100)); then
-    log i 'Invalid amoun of results (%s), defaulting to 10' "${EXA_RESULT_AMOUNT}"
-    EXA_RESULT_AMOUNT=10
-  fi
-
-  declare -A grequest=()
-  grequest['query']="${query}"
-  grequest['tries']="${EXA_TRIES}"
-  grequest['cookies']="${EXA_COOKIES}"
-  grequest['timeout']="${EXA_TIMEOUT}"
-  grequest['user_agent']="${EXA_USER_AGENT}"
-
-  # google params
-  grequest['g_num']="${EXA_RESULT_AMOUNT}"
-
-  if ! google_search grequest; then
-    log e 'Failed to search google'
-    return 1
-  fi
-
-  for ((i = 0; i < GOOGLE_RESULTS; i++)); do
-    if [[ -t 1 ]] && ! ${EXA_NO_COLOR}; then
-      printf '\x1b[38;2;255;169;140m- What: \x1b[38;2;255;232;184m%s\n' "${GOOGLE_RESULT_TITLES[i]}"
-      printf '  \x1b[38;2;195;79;230mLink: \x1b[38;2;189;147;249m%s\x1b[0m\n' "${GOOGLE_RESULT_LINKS[i]}"
-    else
-      printf -- '- What: %s\n  Link: %s\n' "${GOOGLE_RESULT_TITLES[i]}" "${GOOGLE_RESULT_LINKS[i]}"
-    fi
-  done
 }
 
 main "${@}"
